---
driver_plugin: vagrant
driver_config: 
  provisioner: chef_zero

platforms:
- name: centos-6.4_chef-11.4.4
  driver_config: 
    box: opscode-centos-6.4_chef-11.4.4
    box_url:  https://opscode-vm.s3.amazonaws.com/vagrant/opscode_centos-6.4_chef-11.4.4.box
- name: ubuntu-12.04_chef-11.4.4
  run_list:
    - recipe[ubuntu]
  driver_config:
    box: opscode-ubuntu-12.04_chef-11.4.4
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_chef-11.4.4.box

suites:
- name: release
  run_list:
    - recipe[etcd]
  attributes: {}

- name: edge
  run_list:
    - recipe[etcd]
  attributes: {
    etcd: {
      url: "https://dl.dropboxusercontent.com/u/848501/etcd-130813.tar.gz",
      sha256: "7d7e6e71d27aad41345ba41a8b35dc57e01f70524a77cb7968b3c4fdc9f3ade3",
      args: "-f",
      version: "130812"
    }
  }

- name: cluster
  run_list:
    - recipe[etcd]
  attributes: {
    etcd: {
      seed_node: "#{node.name}"
    }
  }
  

